package com.csc205.project1;
import java.math.*;
public class Point {
    public double X;
    public double Y;
    public Point() {
        X = 0.0;
        Y = 0.0;
    }

    public Point(double x, double y) {
        X = x;
        Y = y;
    }

    public double distance(Point pointb)
    {
        double deltaX = pointb.X - this.X;
        double deltaY = pointb.Y - this.Y;
        double distance = Math.sqrt((deltaX * deltaX) + (deltaY * deltaY));
        return distance;
    }

    public double getX()
    {
        return X;
    }

    public void setX(double x)
    {
        X = x;
    }

    public double getY()
    {
        return Y;
    }

    public void setY(double y)
    {
        Y = y;
    }

    public void setPoint(double x, double y)
    {
        X = x;
        Y = y;
    }

    public void shiftX(double n)
    {
        X = X + n;
    }


    public void shiftY(double n)
    {
        Y = Y + n;
    }

    public void rotate(double angle) //This was entirely autogenerated by tabnine
    {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        double newX = cos * X - sin * Y;
        double newY = sin * X + cos * Y;
        X = newX;
        Y = newY;

    }

    public String toString()
    {

        return "Point: (X = " + X + ", Y = " + Y + ")";
    }
}
